# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Main API

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    branches: [ pretesting ]
  pull_request:
    branches: [ pretesting ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        ref: pretesting
    - run: npm install
    - run: npm run build
    - run: cp /deploy/production/.env ./dist/.env
    - run: cp /deploy/production/spGoogle.json ./dist/spGoogle.json
    - run: cp -R ./templates ./dist/templates
    - run: runuser -l api -c "pm2 restart main"
