# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Release API

on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: "Log level"
                required: true
                default: "warning"
    push:
        branches: [release]

jobs:
    build:
        runs-on: prod2
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: release
            - run: npm i
            - run: npm run build
            - run: /home/actions_runner/start_server.sh
