# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy pretesting API

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
  push:
    branches: [pretesting]

jobs:
  build:
    runs-on: pretesting
    steps:
      - uses: actions/checkout@v2
        with:
          ref: pretesting
      - run: npm i
      - run: npm run build
      - run: cp /home/actions_runner_pretesting/.env ./dist/.env
      - run: cp /home/actions_runner_pretesting/spGoogle.json ./dist/spGoogle.json
      - run: cp -R ./templates ./dist/templates
      - run: pm2 restart pretesting
